@echo off

echo Getting Pkger
go get github.com/markbates/pkger/cmd/pkger

echo Packaging web resources
pkger -o web

echo Correct pkger package name (https://github.com/markbates/pkger/issues/56)
more +1 .\web\pkged.go > web\pkged.go.tmp
@echo // See ./update-static.bat to automatically regenerate > .\web\pkged.go
@echo // File automatically generated by pkger. DO NOT EDIT >> .\web\pkged.go
@echo( >> .\web\pkged.go
@echo package web >> .\web\pkged.go
more .\web\pkged.go.tmp >> .\web\pkged.go
del .\web\pkged.go.tmp

echo Getting Pigeon
go get github.com/mna/pigeon@HEAD

echo Getting GoImports
go get golang.org/x/tools/cmd/goimports

echo Compiling peg
pigeon predicate/logselect.peg | goimports > predicate/logselect.go